### ISSUE TITLE
Not able to compile python version under Windows

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#130]
I am not able to compile the python version under Windows.
The error is pretty short: `../src/iopae.cpp:36:19: fatal error: regex.h: No such file or directory`

The regular regex libs are usually heavily POSIX related and thus not available for Windows. Is there any way to make verovio compilable under Windows?

I am using MinGW32.

**Comment by lpugin** [comment]
Are you interested in using Plain and Easy import? We could make it excluded with a preprocessor option

**Comment by craigsapp** [comment]
In the long term you can implement regular expressions according to the C++
2011 standard which should be cross platform:
     https://solarianprogrammer.com/2011/10/12/cpp-11-regex-tutorial

Currently available in clang, and is available in GCC v 4.9 and higher (but
note that GCC 4.8 is the most common linux compiler at the moment, so still
difficult to work with).

Note that C++ 2011 regular expressions are different than POSIX regular
expressions:
C++ 2011:
    #include <regex>
Posix (C) regular expressions:
    #include <regex.h>

It seems to be possible in Micrsoft settings:
    https://msdn.microsoft.com/en-us/magazine/Dn519920.aspx

-=+Craig

**Comment by sonovice** [comment]
@lpugin Excluding P&E would be great as I solely need MEI. Thanks a lot, Laurent!
Greetings from Detmold

**Comment by lpugin** [comment]
I pushed a modification to the develop branch. It should work for the Python toolkit with

```python setup.py build_ext --inplace --define NO_PAE_SUPPORT```

or for the C++ toolkit with

```cmake . -DNO_PAE_SUPPORT=OFF```

Keep me posted

**Comment by lpugin** [comment]
Thanks @craigsapp , but since C++11 regex is not easy to work with yet I went for the easy fix ;-)

**Comment by sonovice** [comment]
Thanks @lpugin !

**Comment by sonovice** [comment]
Hm, still getting some errors. The first one was a missing `../src/git_commit..h` that I created manually according to the `get_git_commit.sh` file.
No I have plenty of warnings and an error, logfile: http://pastebin.com/rf70jVgc

I am not a C or C++ programmer so I dont really have a clue what happens... :-/

**Comment by lpugin** [comment]
I think it would be best to try to compile the C++ version with cmake first. Could you try it?

**Comment by sonovice** [comment]
I've installed MinGW32 from scratch, as well as cmake. Still getting this error:
```
C:\Users\Simon\Desktop\verovio-develop\tools>make
Scanning dependencies of target verovio
[  1%] Building CXX object CMakeFiles/verovio.dir/main.cpp.obj
In file included from C:\Users\Simon\Desktop\verovio-develop\tools\main.cpp:22:0:
C:/Users/Simon/Desktop/verovio-develop/tools/../include/vrv/vrv.h:65:56: error: 'va_list' has not been declared
 std::string StringFormatVariable( const char * format, va_list arg );
                                                        ^
CMakeFiles\verovio.dir\build.make:62: recipe for target 'CMakeFiles/verovio.dir/main.cpp.obj' failed
make[2]: *** [CMakeFiles/verovio.dir/main.cpp.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/verovio.dir/all' failed
make[1]: *** [CMakeFiles/verovio.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```

Used commands:
```
cmake -G "MinGW Makefiles" .
mingw32-make
```

**Comment by sonovice** [comment]
Got it! I had to include `<stdarg.h>` in vrv.h in order to use va_list. The python version got compiled flawlessly. Thanks again for the fast support!

**Comment by sonovice** [comment]
Setting the ```m_path``` explicitly to the data folder path breaks the constructor of toolkit. It just exits the program without any information...

**Comment by sonovice** [comment]
Sorry for so many posts in a row... I ended up using the CLI version and simply call it from within python. Too bad verovio python does not work on Windows...

**Comment by lpugin** [comment]
I added a method in the toolkit for setting the resource path. This will need to be improved. The problem is that it is not ideal to have Resource as static. But for now you should be able to do:

tk = verovio.toolkit( False )
tk.setResourcePath( "/absolute/path/to/the/dir" )

I am not sure it will not crash if the path is not valid...

**Comment by sonovice** [comment]
Thanks for the quickfix. But it still quits silently. I tried to track down the problem without any traceback, this is how fare I've gotten:
```
vrv.cpp (109): Glyph glyph( Resources::GetPath() + "/" + fontName + "/" + pdir->d_name , codeStr );
  glyph.cpp (49): pugi::xml_parse_result result = doc.load_file( path.c_str() );
    pugixml.cpp (4057): xml_parse_status size_status = get_file_size(file, size);
```
Somewhere in the function `PUGI__FN xml_parse_status get_file_size(FILE* file, size_t& out_result)` it just stops working.

**Comment by ahankinson** [comment]
Looks like the path concatenation is using forward slashes instead of Windows back slashes.

**Comment by sonovice** [comment]
@ahankinson Windows works either way. You can even mix it. But yes, it's not very platform independent this way...

**Comment by ahankinson** [comment]
well, it looks like it's not able to find the file in the XML result, so my first instinct is that somehow the path is not getting defined correctly.

**Comment by sonovice** [comment]
Strange thing is that the command line version works without problems, even with mixed slashes & backslashes.

**Comment by lpugin** [comment]
Does it work if you change the "/" to "\" in vrv.cpp#L109 ? If yes, we can change is to something cross-platform.

**Comment by sonovice** [comment]
@lpugin No, sorry. The result remains the same.

**Comment by ahankinson** [comment]
Sorry, it's an obvious question but I have to ask (since I've made this mistake before too!): After you changed it in the C++ file did you re-compile Verovio, or did you just try it again with Python?

**Comment by sonovice** [comment]
@ahankinson I've recompiled it properly before trying again.

**Comment by ahankinson** [comment]
OK, just checking!

**Comment by sonovice** [comment]
No problem, I wasn't even sure and just tried it again. I managed to track down the problem to this line (4002 in pugixml.cpp): `fseeko64(file, 0, SEEK_END);`

I just tried replacing the fseeko64 calls with fseek and now it works with python. Maybe there is something wrong with the preprocessor statements?

**Comment by ahankinson** [comment]
Are you using 32-bit Python?

**Comment by sonovice** [comment]
Yes

**Comment by ahankinson** [comment]
Ah, that could be it. fseeko64 is probably a 64-bit operation, so it would probably fail in a 32 bit environment.

**Comment by lpugin** [comment]
Anything we need to change before closing this issue?

**Comment by sonovice** [comment]
I guess the preprocessor definition (pugixml.cpp:3998) gets it wrong since I am not using a 64 bit compiler:
`#elif defined(__MINGW32__) && !defined(__NO_MINGW_LFS) && (!defined(__STRICT_ANSI__) || defined(__MINGW64_VERSION_MAJOR))`

**Comment by lpugin** [comment]
The simplest would be to use a 64-bit Python. If this is not possible I would recommend to see if it can be fixed directly in pugixml https://github.com/zeux/pugixml.

**Comment by sonovice** [comment]
Okay, I will give it a shot. Thanks for the extensive support, @lpugin and @ahankinson !

**Comment by sonovice** [comment]
Sorry for reopening, but today I tried again to compile Verovio for Python x64 with VS 2015 (recommended for Python 3.5 Extensions) on Windows 10.
Here is how far I've come:
Build cmd: `python setup.py build_ext --inplace --define NO_PAE_SUPPORT`

First, all additional compiler arguments (`extra_compile_args=['-std=c++11', '-Wno-write-strings', '-Wno-overloaded-virtual', '-Wno-unused-private-field']`) are not supported by VS. `c++11` get's automatically detected, so I simply removed all the arguments.

Next problem was:
`../include/vrv\vrv.h(16): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory` - Windows just wants `time.h`, no `sys`.

`M_PI` is not defined by default. According to [the docs](https://msdn.microsoft.com/en-us/library/4hwaceh6.aspx), `_USE_MATH_DEFINES` has to be defined before including `<math.h>` in order to use math constants, so I did this to `src/bboxdevicecontext.cpp`, `src/svgdevicecontext.cpp` and `src/view_floating.cpp`.

Next, line 847 in `src/view_floating.cpp` gave an type mismatch error.
Code: `float maxHeightFactor = std::max(0.2, fabs(angle));` - Apparently VS wants `0.2` to be explicitly declared as float: `0.2F`.

`<dirent.h>` is not available under VS. I used [this replacement](http://softagalleria.net/dirent.php), which worked instantly.

`src/git_commit.h` was not there, so I created the file with the following content (according to `get_git_commit.sh`):
`#define GIT_COMMIT "[undefined]"`

Back in file `vrv.h` the structure `timeval` was undeclared. I simply added it:
```
typedef struct timeval {
  long tv_sec;
  long tv_usec;
} timeval;
```

Since `time.h` is not the same under Windows, I had to comment out the body of `void LogElapsedTimeEnd(const char *msg)` (Line 218) and `void LogElapsedTimeEnd(const char *msg)` (Line 223) in `vrv.cpp`. Programming a replacement for `gettimeofday` would be a better solution...

The `back_inserter` method in `src/midi/MidiMessage.cpp` needs `<iterator>` to be included.

**Comment by sonovice** [comment]
Sorry for reopening, but today I tried again to compile Verovio for Python x64 with VS 2015 (recommended for Python 3.5 Extensions) on Windows 10.
Here is how far I've come:
Build cmd: `python setup.py build_ext --inplace --define NO_PAE_SUPPORT`

First, all additional compiler arguments (`extra_compile_args=['-std=c++11', '-Wno-write-strings', '-Wno-overloaded-virtual', '-Wno-unused-private-field']`) are not supported by VS. `c++11` get's automatically detected, so I simply removed all the arguments.

Next problem was:
`../include/vrv\vrv.h(16): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory` - Windows just wants `time.h`, no `sys`.

`M_PI` is not defined by default. According to [the docs](https://msdn.microsoft.com/en-us/library/4hwaceh6.aspx), `_USE_MATH_DEFINES` has to be defined before including `<math.h>` in order to use math constants, so I did this to `src/bboxdevicecontext.cpp`, `src/svgdevicecontext.cpp` and `src/view_floating.cpp`.

Next, line 847 in `src/view_floating.cpp` gave an type mismatch error.
Code: `float maxHeightFactor = std::max(0.2, fabs(angle));` - Apparently VS wants `0.2` to be explicitly declared as float: `0.2F`.

`<dirent.h>` is not available under VS. I used [this replacement](http://softagalleria.net/dirent.php), which worked instantly.

`src/git_commit.h` was not there, so I created the file with the following content (according to `get_git_commit.sh`):
`#define GIT_COMMIT "[undefined]"`

Back in file `vrv.h` the structure `timeval` was undeclared. I simply added it:
```
typedef struct timeval {
  long tv_sec;
  long tv_usec;
} timeval;
```

Since `time.h` is not the same under Windows, I had to comment out the body of `void LogElapsedTimeEnd(const char *msg)` (Line 218) and `void LogElapsedTimeEnd(const char *msg)` (Line 223) in `vrv.cpp`. Programming a replacement for `gettimeofday` would be a better solution...

The `back_inserter` method in `src/midi/MidiMessage.cpp` needs `<iterator>` to be included.

After all these changes, Verovio compiles...

**Comment by lpugin** [comment]
I just pushed fixes to the https://github.com/rism-ch/verovio/tree/develop-python-win32 branch. Please have a try. A few comments

> M_PI is not defined by default. According to the docs, _USE_MATH_DEFINES has to be defined before including <math.h> in order to use math constants, so I did this to src/bboxdevicecontext.cpp, src/svgdevicecontext.cpp and src/view_floating.cpp.

This was not clear and it not fixed

> Next, line 847 in src/view_floating.cpp gave a type mismatch error.
Code: float maxHeightFactor = std::max(0.2, fabs(angle)); - Apparently VS wants 0.2 to be explicitly declared as float: 0.2F.

This is hopefully fixed with the ```#define NOMINMAX``` in ```win32.h```

> src/git_commit.h was not there, so I created the file with the following content (according to get_git_commit.sh):
#define GIT_COMMIT "[undefined]"

This will remain the case

> The back_inserter method in src/midi/MidiMessage.cpp needs <iterator> to be included.

@craigsapp ?

**Comment by sonovice** [comment]
>> M_PI is not defined by default. According to the docs, _USE_MATH_DEFINES has to be defined before including math.h in order to use math constants, so I did this to src/bboxdevicecontext.cpp, src/svgdevicecontext.cpp and src/view_floating.cpp.

>This was not clear and it not fixed

M_PI ist just not defined by default when including math.h in Visual Studio. `_USE_MATH_DEFINES` needs to be defined first before including math.h, that's all.



>> src/git_commit.h was not there, so I created the file with the following content (according to get_git_commit.sh):
#define GIT_COMMIT "[undefined]"

> This will remain the case

I'm afraid that this will be a problem for Windows because there is no (Bourne) shell that would create the file when compiling. Maybe the responsible script can be written in pure C/C++?

Anyway, thank you so far, I will try the win32 branch tomorrow!
