### ISSUE TITLE
Space harm appropriately

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#358]
As `<harm>` text length is increased, the `<harm>` text line rises for some reason.  This rise eventually pushes the systems further apart as well.   The example output on the left has short `<harm>` text, while the one on the right has long `<harm>` text.

<img width="1195" alt="screen shot 2016-11-17 at 23 18 28" src="https://cloud.githubusercontent.com/assets/3487289/20421979/49cf7722-ad1c-11e6-988a-bb006bd06666.png">

Short harm example data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-11-17 22:57:12</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-76b1067</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000000818709889">
                        <staffGrp xml:id="m-0000000992362694">
                            <staffDef xml:id="staffdef-0000001281795456" clef.shape="G" clef.line="2" key.sig="0" meter.count="3" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001997153672">
                        <measure xml:id="measure-L1" n="0">
                            <staff xml:id="staff-0000001658788722" n="1">
                                <layer xml:id="layer-L1F2" n="1">
                                    <note xml:id="note-L7F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L8F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L9F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001869175712" staff="1" tstamp="1.000000">F</harm>
                            <harm xml:id="harm-0000001733895302" staff="1" tstamp="2.500000">B♭</harm>
                        </measure>
                        <measure xml:id="measure-L10">
                            <staff xml:id="staff-L10F2" n="1">
                                <layer xml:id="layer-L10F2" n="1">
                                    <note xml:id="note-L11F2" dots="1" dur="4" oct="4" pname="f" accid.ges="n" stem.dir="up" />
                                    <note xml:id="note-L12F2" dur="4" accid="f" oct="4" pname="a" stem.dir="up" />
                                    <note xml:id="note-L13F2" dur="8" accid="f" oct="4" pname="b" stem.dir="down" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000666816101" staff="1" tstamp="1.000000">E♭</harm>
                        </measure>
                        <measure xml:id="measure-L14">
                            <staff xml:id="staff-L14F2" n="1">
                                <layer xml:id="layer-L14F2" n="1">
                                    <note xml:id="note-L15F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L16F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L17F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000038480265" staff="1" tstamp="1.000000">B♭</harm>
                            <harm xml:id="harm-0000002029936609" staff="1" tstamp="3.500000">E♭</harm>
                        </measure>
                        <measure xml:id="measure-L18">
                            <staff xml:id="staff-L18F2" n="1">
                                <layer xml:id="layer-L18F2" n="1">
                                    <note xml:id="note-L19F2" dur="2" oct="4" pname="e" accid.ges="n" stem.dir="up" />
                                    <rest xml:id="rest-L20F2" dur="4" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001555251778" staff="1" tstamp="1.000000">A♭</harm>
                        </measure>
                        <measure xml:id="measure-L21">
                            <staff xml:id="staff-L21F2" n="1">
                                <layer xml:id="layer-L21F2" n="1">
                                    <note xml:id="note-L22F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L23F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L24F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000388685678" staff="1" tstamp="1.000000">F</harm>
                            <harm xml:id="harm-0000000788227284" staff="1" tstamp="2.500000">B♭</harm>
                        </measure>
                        <measure xml:id="measure-L25">
                            <staff xml:id="staff-L25F2" n="1">
                                <layer xml:id="layer-L25F2" n="1">
                                    <note xml:id="note-L26F2" dots="1" dur="4" oct="4" pname="f" accid.ges="n" stem.dir="up" />
                                    <note xml:id="note-L27F2" dur="4" accid="f" oct="4" pname="a" stem.dir="up" />
                                    <note xml:id="note-L28F2" dur="8" accid="f" oct="4" pname="b" stem.dir="down" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000472998928" staff="1" tstamp="1.000000">E♭</harm>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Long harm MEI

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-11-17 22:55:33</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-76b1067</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000002093535509">
                        <staffGrp xml:id="m-0000001728054073">
                            <staffDef xml:id="staffdef-0000000835962883" clef.shape="G" clef.line="2" key.sig="0" meter.count="3" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000543394331">
                        <measure xml:id="measure-L1" n="0">
                            <staff xml:id="staff-0000000022147551" n="1">
                                <layer xml:id="layer-L1F2" n="1">
                                    <note xml:id="note-L7F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L8F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L9F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001206274047" staff="1" tstamp="1.000000">F minor-seventh</harm>
                            <harm xml:id="harm-0000000079211563" staff="1" tstamp="2.500000">B♭ dominant</harm>
                        </measure>
                        <measure xml:id="measure-L10">
                            <staff xml:id="staff-L10F2" n="1">
                                <layer xml:id="layer-L10F2" n="1">
                                    <note xml:id="note-L11F2" dots="1" dur="4" oct="4" pname="f" accid.ges="n" stem.dir="up" />
                                    <note xml:id="note-L12F2" dur="4" accid="f" oct="4" pname="a" stem.dir="up" />
                                    <note xml:id="note-L13F2" dur="8" accid="f" oct="4" pname="b" stem.dir="down" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001458768941" staff="1" tstamp="1.000000">E♭ maj</harm>
                        </measure>
                        <measure xml:id="measure-L14">
                            <staff xml:id="staff-L14F2" n="1">
                                <layer xml:id="layer-L14F2" n="1">
                                    <note xml:id="note-L15F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L16F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L17F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000042159528" staff="1" tstamp="1.000000">B♭ minor-seventh</harm>
                            <harm xml:id="harm-0000000133745035" staff="1" tstamp="3.500000">E♭ dominant</harm>
                        </measure>
                        <measure xml:id="measure-L18">
                            <staff xml:id="staff-L18F2" n="1">
                                <layer xml:id="layer-L18F2" n="1">
                                    <note xml:id="note-L19F2" dur="2" oct="4" pname="e" accid.ges="n" stem.dir="up" />
                                    <rest xml:id="rest-L20F2" dur="4" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001667422194" staff="1" tstamp="1.000000">A♭ minor-major</harm>
                        </measure>
                        <measure xml:id="measure-L21">
                            <staff xml:id="staff-L21F2" n="1">
                                <layer xml:id="layer-L21F2" n="1">
                                    <note xml:id="note-L22F2" dots="1" dur="4" oct="5" pname="c" accid.ges="n" stem.dir="down" />
                                    <note xml:id="note-L23F2" dur="4" accid="f" oct="4" pname="b" stem.dir="down" />
                                    <note xml:id="note-L24F2" dur="8" accid="f" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000001531304268" staff="1" tstamp="1.000000">F minor-seventh</harm>
                            <harm xml:id="harm-0000000830883460" staff="1" tstamp="2.500000">B♭ dominant</harm>
                        </measure>
                        <measure xml:id="measure-L25">
                            <staff xml:id="staff-L25F2" n="1">
                                <layer xml:id="layer-L25F2" n="1">
                                    <note xml:id="note-L26F2" dots="1" dur="4" oct="4" pname="f" accid.ges="n" stem.dir="up" />
                                    <note xml:id="note-L27F2" dur="4" accid="f" oct="4" pname="a" stem.dir="up" />
                                    <note xml:id="note-L28F2" dur="8" accid="f" oct="4" pname="b" stem.dir="down" />
                                </layer>
                            </staff>
                            <harm xml:id="harm-0000000868591516" staff="1" tstamp="1.000000">E♭ maj</harm>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
Make them short ;-)

**Comment by craigsapp** [comment]
Here is another case:

http://verovio.humdrum.org/?file=chopin/mazurkas/mazurka17-4.krn&filter=metlev%20-caemxhm

<img width="717" alt="screen shot 2016-12-18 at 09 34 17" src="https://cloud.githubusercontent.com/assets/3487289/21295232/740cc5b6-c505-11e6-8c2b-bb06cdef008c.png">

Using the `<verse>` system, the overlap is resolved:

http://verovio.humdrum.org/?file=chopin/mazurkas/mazurka17-4.krn&filter=metlev%20-caetext

But the problem is that I cannot attach lyrics to rests or to time offsets from a note attack:

<img width="743" alt="screen shot 2016-12-18 at 09 40 35" src="https://cloud.githubusercontent.com/assets/3487289/21295284/5762e4da-c506-11e6-9fcd-84ac29432825.png">

It would be nice if the `<harm>` and `<verse>` systems had similar capabilities: both collision avoidance (currently only in `<verse>` and attachable to rest or arbitrary `@tstamp` locations (currently on in `<harm>`.

**Comment by craigsapp** [comment]
As the overlap increases, the veritcal offset increases:

<img width="750" alt="screen shot 2016-12-18 at 09 59 20" src="https://cloud.githubusercontent.com/assets/3487289/21295380/c1402afa-c508-11e6-8d3d-99bb55568f2d.png">

So I suspect that there is a bug: overlap avoidance is being done, but it is applied to vertical offset rather than horizontal offset.

**Comment by lpugin** [comment]
There is a flaw in the algorithm. What is happening is that all the harm indications are aligned vertically (which means here pilled up in order to avoid collisions). Then they are all aligned with the highest one, which produces this. They should obviously be spaced before all this happening.

**Comment by sonovice** [comment]
> 
> 
> There is a flaw in the algorithm. What is happening is that all the harm indications are aligned vertically (which means here pilled up in order to avoid collisions). Then they are all aligned with the highest one, which produces this. They should obviously be spaced before all this happening.

Could you maybe tell me where this happens in the code, please? I have the same problem right now and would take a look at it, but can't seem to find the right position...

**Comment by sonovice** [comment]
Responsible for the gaps are these lines of code, especially line 363 in this case: https://github.com/rism-ch/verovio/blob/13c67749cd8ee9b452ad67c18a649f7b8b9cd811/src/floatingobject.cpp#L355-L364


I am still not able to find a solution. Any help would be highly appreciated.

**Comment by lpugin** [comment]
What needs to be added is a pass in the layout algorithm that spaces the `harm` before doing the vertical adjustment. This is missing, so it it not quite a matter of fixing existing code. (The additional problem is that adding this with the current justification algorithm will not work properly, so improving the justification algorithm should be done first. This is a quite significant task.) I will try to scaffold something.

**Comment by sonovice** [comment]
> What needs to be added is a pass in the layout algorithm that spaces the `harm` before doing the vertical adjustment. This is missing, so it it not quite a matter of fixing existing code. (The additional problem is that adding this with the current justification algorithm will not work properly, so improving the justification algorithm should be done first. This is a quite significant task.) I will try to scaffold something.

Thank you so much, Laurent! If I can help in any way, please let me know.

**Comment by sonovice** [comment]
I really don't want to rush and I know that you certainly have a lot else on your plate. But do you think it's possible to look at this problem by the end of the month? I have the release date for an app breathing down my neck, and until recently I wasn't aware that solving the bug would require such profound changes that I unfortunately don't know the framework well enough for.

It would be great if you could just realistically estimate if the necessary changes are feasible in the next 2 weeks and if I can help somehow? Sorry if I lean too far out of the window. As I said, I don't want to pass on my own time pressure, but at the moment I'm a bit lost... 😟

**Comment by lpugin** [comment]
I am afraid it will not be feasible for me to free some time for this in the next two weeks. 

Now following up on your last edit: you should be able to manage multiple lines of harm text using  `@n`, and they should be handled properly. Have you tried this?

**Comment by lpugin** [comment]
Could you send a sample MEI file? I can have a look this afternoon if there is at all a not too complicated fix for this.

**Comment by sonovice** [comment]
> Could you send a sample MEI file? I can have a look this afternoon if there is at all a not too complicated fix for this.

Here is a MusicXML file and the MEI conversion done by Verovio: [example.zip](https://github.com/rism-ch/verovio/files/2983331/example.zip)

Thank you for taking the time.

**Comment by lpugin** [comment]
OK, I implemented something 73fa29830199337ecc1e13ee0282eed19e67d3e6
As I said, because of some limitations in the justification algorithm this can still fail in some cases. Have a try and keep me posted.

**Comment by craigsapp** [comment]
You can use the `--spacing-non-linear` and/or `--spacing-linear` parameters to stretch the layout spacing so that the longest `<chord>` does not collide with the next `<chord>`:

<img width="1206" alt="Screen Shot 2019-03-19 at 9 13 00 AM" src="https://user-images.githubusercontent.com/3487289/54608201-95908580-4a26-11e9-8389-38cfc76b0d6b.png">

The command-line options to generate the above rendering:

```bash
verovio --no-header --spacing-non-linear 0.65 example.musicxml
```

In Javascript toolkit, the options are named `spacingNonLinear` and `spacingLinear`. 


spacingLinear parameter range: default: 0.25; min: 0.00; max: 1.00.

spacingNonLinear parameter range: default: 0.60; min: 0.00; max: 1.00

**Comment by lpugin** [comment]
![image](https://user-images.githubusercontent.com/689412/54670988-364d7680-4af5-11e9-8c20-a86c501d3f8e.png)

**Comment by sonovice** [comment]
@lpugin Thank you so much! It works like a charm in most cases.

@craigsapp I already increased the spacing between notes but I needed a generic solution for several hundred songs in an iPhone App. The limited screen spaces makes your solution not viable. But thank you very much anyways!

**Comment by lpugin** [comment]
Great! What is the App? Looking forward to testing it.

**Comment by sonovice** [comment]
> Great! What is the App? Looking forward to testing it.

It's not released yet (2 more weeks ;) ) but the name is "Cantico".

**Comment by sonovice** [comment]
Here is an [example](https://github.com/rism-ch/verovio/files/2988601/example.zip), where things are still slightly off:
![Image-1](https://user-images.githubusercontent.com/8217108/54690851-927abf80-4b22-11e9-9c2d-b24b3261d8cd.jpg)

It happens, when there are 2 (or more) voices and the position of the harm elements switches between these voices.

**Comment by earboxer** [comment]
What is the status of the following?

- [ ] a pass in the layout algorithm that spaces the harm before doing the vertical adjustment.
  (is this what https://github.com/rism-ch/verovio/commit/73fa29830199337ecc1e13ee0282eed19e67d3e6 was doing?)
- [ ] improving the justification algorithm (quite significant task.)

**Comment by bbloomf** [comment]
Yes, what is the status of this?  Has there been a regression?  The demonstration [here](https://www.verovio.org/test-suite.xhtml?cat=harm#example-harm-004) appears to be the same music as @lpugin posted here on March 20, 2019, but the overlap is not being prevented, and the extra vertical space is present.

**Comment by bbloomf** [comment]
I did a bit of digging, and 3dd860ad5 appears to have broken this, apparently because `this->HasContentBB()` is always returning false.

**Comment by lpugin** [comment]
Thanks for looking at this. Unfortunately, I do not understand what regression you are talking about. Can you be more explicit about it?

(As explained in this thread, spacing of harm indications is not expected to work because it has never been properly implemented.)

**Comment by bbloomf** [comment]
@lpugin What I meant is that before 3dd860a, running `verovio` on [harm-004.mei](https://www.verovio.org/test-suite.xhtml?cat=harm#example-harm-004) produces output like in [your comment above](https://github.com/rism-ch/verovio/issues/358#issuecomment-474739224), but that commit introduced a change that causes `verovio` to produce output like what is shown on [the Test Suite page](https://www.verovio.org/test-suite.xhtml?cat=harm#example-harm-004)

**Comment by lpugin** [comment]
You are right, it used to work better

![image](https://user-images.githubusercontent.com/689412/106560290-15467100-6527-11eb-9dfe-d7b99dfffd38.png)

I'll have a look

**Comment by lpugin** [comment]
We are now back to previous behaviour

![image](https://user-images.githubusercontent.com/689412/106788522-589cfe80-6651-11eb-91b6-39f86c85c39c.png)
